import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-large")
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-4o-mini")
EMBEDDING_DIMENSION = int(os.getenv("EMBEDDING_DIMENSION", 3072))

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_ENVIRONMENT = os.getenv("PINECONE_ENVIRONMENT")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "dispensery-search")

REDIS_LANGCACHE_SERVER_URL = os.getenv("REDIS_LANGCACHE_SERVER_URL")
REDIS_LANGCACHE_API_KEY = os.getenv("REDIS_LANGCACHE_API_KEY")
REDIS_LANGCACHE_CACHE_ID = os.getenv("REDIS_LANGCACHE_CACHE_ID")
REDIS_LANGCACHE_SIMILARITY_THRESHOLD = float(os.getenv("REDIS_LANGCACHE_SIMILARITY_THRESHOLD", 0.9))
